apiVersion: v2
name: geonetwork
description: A Helm chart for running GeoNetwork, Elastic Seach and Kibana, connecting to a PostGIS database
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

keywords:
  - GeoNetwork
  - GIS
home: https://github.com/SpatialFocus/helm-charts
sources:
  - https://sourceforge.net/projects/geonetwork
maintainers:
  - name: pergerch
    email: christoph.perger@spatial-focus.net
    url: https://github.com/pergerch
  - name: SpatialFocus
    email: office@spatial-focus.net
    url: https://github.com/SpatialFocus
icon: https://avatars.githubusercontent.com/u/10947235?s=200&v=4
