apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gn-chart.fullname" . }}-elasticsearch
  labels:
  {{- include "gn-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "gn-chart.fullname" . }}-elasticsearch
    {{- include "gn-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "gn-chart.fullname" . }}-elasticsearch
      {{- include "gn-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1G -Xmx1G
        - name: discovery.type
          value: single-node
#        - name: KUBERNETES_CLUSTER_DOMAIN
#          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag | default .Chart.AppVersion }}
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: esdata
        persistentVolumeClaim:
          claimName: {{ include "gn-chart.fullname" . }}-esdata
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gn-chart.fullname" . }}-elasticsearch
  labels:
  {{- include "gn-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "gn-chart.fullname" . }}-elasticsearch
  {{- include "gn-chart.selectorLabels" . | nindent 4 }}
  ports:
  - port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gn-chart.fullname" . }}-esdata
  labels:
  {{- include "gn-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storageRequest | quote }}